/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package labpractico6;



import java.awt.Color;
import java.util.TreeSet;






/**
 *
 * @author Usuario
 */
public class Menu extends javax.swing.JFrame {
  public static TreeSet<Producto> listaProductos =new TreeSet<>();
    

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.getContentPane().setBackground(Color.YELLOW);
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuPRODUCTOS = new javax.swing.JMenuItem();
        jMenuConsulta = new javax.swing.JMenu();
        jMenuRUBRO = new javax.swing.JMenuItem();
        jMenuNOMBRE = new javax.swing.JMenuItem();
        jMenuPRECIO = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        escritorio.setToolTipText("");
        escritorio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Elbarto.jpg"))); // NOI18N

        escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 936, 775));

        jMenuBar1.setBackground(new java.awt.Color(153, 0, 153));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setForeground(new java.awt.Color(153, 0, 153));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu1.setBackground(new java.awt.Color(102, 0, 102));
        jMenu1.setText("Administracion");

        jMenuPRODUCTOS.setText("Productos");
        jMenuPRODUCTOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPRODUCTOSActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuPRODUCTOS);

        jMenuBar1.add(jMenu1);

        jMenuConsulta.setBackground(new java.awt.Color(102, 0, 102));
        jMenuConsulta.setText("Consultas");

        jMenuRUBRO.setText("Por rubro");
        jMenuRUBRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRUBROActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jMenuRUBRO);

        jMenuNOMBRE.setText("Por nombre");
        jMenuNOMBRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNOMBREActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jMenuNOMBRE);

        jMenuPRECIO.setText("Por precio");
        jMenuPRECIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPRECIOActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jMenuPRECIO);

        jMenuBar1.add(jMenuConsulta);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuNOMBREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNOMBREActionPerformed

        // TODO add your handling code here:
        
        
        escritorio.removeAll();
        escritorio.repaint();
        PorNombre bpn= new PorNombre();
        bpn.setVisible(true);
        
        //agregamos a nuestro escritorio la ventana
        escritorio.add(bpn);
        escritorio.moveToFront(bpn);
        
    }//GEN-LAST:event_jMenuNOMBREActionPerformed

    private void jMenuRUBROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRUBROActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        PorRubro bpr= new PorRubro();
        bpr.setVisible(true);
        
        
        //agregamos a nuestro escritorio la ventana
        
        escritorio.add(bpr);
        escritorio.moveToFront(bpr);
    }//GEN-LAST:event_jMenuRUBROActionPerformed

    private void jMenuPRECIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPRECIOActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        PorPrecio bpp=new PorPrecio();
        bpp.setVisible(true);
        
        escritorio.add(bpp);
        escritorio.moveToFront(bpp);
    }//GEN-LAST:event_jMenuPRECIOActionPerformed

    private void jMenuPRODUCTOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPRODUCTOSActionPerformed


        escritorio.removeAll();
        escritorio.repaint();
        AgregarProductos mproduc=new AgregarProductos();
        mproduc.setVisible(true);
        
        escritorio.add(mproduc);
        escritorio.moveToFront(mproduc);
    }//GEN-LAST:event_jMenuPRODUCTOSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
        
       
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConsulta;
    private javax.swing.JMenuItem jMenuNOMBRE;
    private javax.swing.JMenuItem jMenuPRECIO;
    private javax.swing.JMenuItem jMenuPRODUCTOS;
    private javax.swing.JMenuItem jMenuRUBRO;
    // End of variables declaration//GEN-END:variables

    public void cargarProductos(Producto pp){
        
        listaProductos.add(pp);
        
    }



}
